phrase = "Giraffe Academy"
print(phrase)
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(phrase + " " + phrase)
print(len(phrase))
print(phrase.index("G"))
print(phrase.index("Acad"))
